name: just_audio_example
description: Demonstrates how to use the just_audio plugin.
publish_to: 'none'

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  just_audio_platform_interface: ^4.2.1
  # just_audio_platform_interface:
  #   path: ../just_audio_platform_interface
  audio_service: ^0.18.10
  audio_session: ^0.1.14
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.3.0
  rxdart: '>=0.26.0 <0.28.0'
  http: ^1.1.0
  connectivity_plus: ^4.0.1
  flutter_lyric: ^2.0.4+6
  get_it: ^7.6.0

  cached_network_image: ^3.2.3
  on_audio_query: ^2.9.0
  marquee: ^2.2.3
  flutter_localizations:
    sdk: flutter
  flutter_archive: ^5.0.0
  permission_handler: ^10.4.3
  palette_generator: ^0.3.3+2
  dart_des: ^1.0.2
  share_plus: ^7.0.2
  file_picker: ^5.3.3
  url_launcher: ^6.1.12
  app_links: ^3.4.3
  audiotagger: ^2.2.1
  flip_card: ^0.7.0
  sliding_up_panel: ^2.0.0+1
  material_design_icons_flutter: ^7.0.7296
  provider: ^6.0.5
  path_provider: ^2.0.15
  metadata_god: ^0.5.0
  just_audio: ^0.9.34
  just_audio_background: ^0.0.1-beta.10
  miniplayer: ^1.0.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  # integration_test: ^1.0.1
  test: ^1.16.5

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - audio/

